name: Build

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -qq scons gcc-avr binutils-avr avr-libc

      - name: Build
        run: scons
        
      - name : upload
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: boot
          path: ${{ github.workspace }}/build/
